AllCops:
  NewCops: enable
  TargetRubyVersion: 2.3
  SuggestExtensions: false
  Exclude:
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - ".git/**/*"
    - "temp/**/*"

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

require: rubocop-rspec

RSpec/MultipleExpectations:
  Max: 5
RSpec/ExampleLength:
  Max: 20
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Lint/RedundantCopDisableDirective:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 15

Bundler/DuplicatedGem:
  Enabled: false
